apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brave-browser
  name: brave
spec:
  template:
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.1.1 
        searches:
          - brave.svc.cluster.local 
          - svc.cluster.local 
          - cluster.local
        options:
          - name: ndots
            value: "5"
