apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: zeathe/bravebrowser
  newTag: 0.2.2


bases:
- ../../base
patchesStrategicMerge:
- brave-secrets.yml
- brave-deploy.yml
