kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: brave-pvc-volume
  namespace: brave-browser
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: nfs-client
